version: '3'
services:
  db:
    image: mysql
    container_name: db_container
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - '3306:3306'
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/

    networks:
      - app_network

  api:
    image: node
    container_name: api_container
    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=${TZ}
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm start
    networks:
      - app_network

    depends_on:
      - db
      
networks:
  app_network:

volumes:
  mysql_data: